### 프로젝트 등록
POST http://localhost:8080/projects
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2ODc2MTcyLCJleHAiOjE2NjY4Nzk3NzJ9.WOuSuaw4zZ1hYyKmgWALlcZY1nxXm3woJTbzp1O4r0VXsHJqZs0nUrSfrtAbJ0AskXTI_q563hKMnyfiiPcTnA

{
  "content": "내용",
  "id": 0,
  "maxTotal": 5,
  "projectSkills": [
    {
      "name": "spring boot",
      "projectId": 0
    },
    {
      "name": "react",
      "projectId": 0
    }
  ],
  "title": "웹 프로젝트"
}

### 프로젝트 수정
PUT http://localhost:8080/projects
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2NDU3OTM0LCJleHAiOjE2NjY0NjE1MzR9.yu9eiKxcy6HFwEGtgyaxbyIrddvCyv_Dc3b5gLuoget8n_uPiUTw2hWUhu4m0hmxW9BWAsiUinCgLlQIjbnUlA

{
  "content": "string",
  "id": 2,
  "maxTotal": 6,
  "projectSkills": [
    {
      "id": 0,
      "name": "java"
    },
    {
      "id": 0,
      "name": "spring"
    }
  ],
  "title": "string"
}

### 프로젝트 삭제
DELETE http://localhost:8080/projects/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2NDU3OTM0LCJleHAiOjE2NjY0NjE1MzR9.yu9eiKxcy6HFwEGtgyaxbyIrddvCyv_Dc3b5gLuoget8n_uPiUTw2hWUhu4m0hmxW9BWAsiUinCgLlQIjbnUlA

### 프로젝트 스킬 삭제
DELETE http://localhost:8080/projects/2/skill
Content-Type: application/json

### 프로젝트 댓글 추가
POST http://localhost:8080/projects/1/comments
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2ODc2MTcyLCJleHAiOjE2NjY4Nzk3NzJ9.WOuSuaw4zZ1hYyKmgWALlcZY1nxXm3woJTbzp1O4r0VXsHJqZs0nUrSfrtAbJ0AskXTI_q563hKMnyfiiPcTnA

{
  "content": "끝나는 날이 언제인가요?",
  "projectId": 1
}

### 프로젝트 댓글 수정
PUT http://localhost:8080/projects/1/comments
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2ODc2MTcyLCJleHAiOjE2NjY4Nzk3NzJ9.WOuSuaw4zZ1hYyKmgWALlcZY1nxXm3woJTbzp1O4r0VXsHJqZs0nUrSfrtAbJ0AskXTI_q563hKMnyfiiPcTnA

{
  "id": 1,
  "content": "업데이트!!",
  "projectId": 1
}

### 프로젝트 댓글 삭제
DELETE http://localhost:8080/projects/comments/2
Content-Type: application/json