### 프로젝트 등록
POST http://localhost:8080/projects
Content-Type: application/json
X-AUTH-TOCKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2MzcxNjIwLCJleHAiOjE2NjYzNzUyMjB9.7J78CUQpxpvGQpz7tLXBHgpo5RXwfTOV82RUa6QYKRfE-TpxydsHyXcnGkaBjLjoW6RGkxLIzppzDEUWLrGX_g

{
  "content": "내용",
  "id": 0,
  "maxTotal": 5,
  "projectSkills": [
    {
      "name": "spring boot",
      "projectId": 0
    },
    {
      "name": "react",
      "projectId": 0
    }
  ],
  "title": "웹 프로젝트"
}

### 프로젝트 수정
PUT http://localhost:8080/projects
Content-Type: application/json
X-AUTH-TOCKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aGdtbDM1MkBnbWFpbC5jb20iLCJqdGkiOiIxIiwiaWF0IjoxNjY2MzcxNjIwLCJleHAiOjE2NjYzNzUyMjB9.7J78CUQpxpvGQpz7tLXBHgpo5RXwfTOV82RUa6QYKRfE-TpxydsHyXcnGkaBjLjoW6RGkxLIzppzDEUWLrGX_g

{
  "content": "string",
  "id": 1,
  "maxTotal": 6,
  "projectSkills": [
    {
      "id": 0,
      "name": "Django"
    }
  ],
  "title": "string"
}