spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${jdbc.url}
      username: ${jdbc.username}
      password: ${jdbc.password}

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false