spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hodb.cvqao9ppajc1.ap-northeast-2.rds.amazonaws.com:3306/baseCommunity?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${jdbc.username}
    password: ${jdbc.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: basecommunity.web@gmail.com
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  jwt:
    secret: ${jwt.secret}

  servlet:
    multipart:
      max-file-size: 1MB

  batch:
    job:
      names: ${job.name:NONE}

dir:
  UrlPath: /files
  LocalPath: D:\dev\Project\BaseCommunity-BE\files

api:
  external-work:
    url: "http://openapi.work.go.kr/opi/opi/opia/wantedApi.do"
    jobCode: "|133100|133101|133102|133200|133201|133202|133203|133204|133205|133206|133207|133300|133301|133302|133900"
    authKey: ${api.authKey}
    display: "100"

