spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baseCommunity?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: basecommunity.web@gmail.com
    password: password
    properties:
      mail:
        smtp:
          starttls:
            enable: true